export const CapitaLandMallsList = [
  {
    id: 1,
    name: "Aperia Mall",
    link: "https://www.capitaland.com/sg/malls/aperia/en.html",
    pic: "./assets/capitaland/CLmall1.png",
  },
  {
    id: 2,
    name: "Bedok Mall",
    link: "https://www.capitaland.com/sg/malls/bedokmall/en.html",
    pic: "./assets/capitaland/CLmall2.png",
  },
  {
    id: 3,
    name: "Bugis Junction",
    link: "https://www.capitaland.com/sg/malls/bugisjunction/en.html",
    pic: "./assets/capitaland/CLmall3.png",
  },
  {
    id: 4,
    name: "Bugic Plus",
    link: "https://www.capitaland.com/sg/malls/bugisplus/en.html",
    pic: "./assets/capitaland/CLmall4.png",
  },
  {
    id: 5,
    name: "Bugis Street",
    link: "https://www.capitaland.com/sg/malls/bugis-street/en.html",
    pic: "./assets/capitaland/CLmall5.png",
  },
  {
    id: 6,
    name: "Bukit Panjang Plaza",
    link: "https://www.capitaland.com/sg/malls/bukitpanjangplaza/en.html",
    pic: "./assets/capitaland/CLmall6.png",
  },
  {
    id: 7,
    name: "Clarke Quay",
    link: "https://www.capitaland.com/sg/malls/clarkequay/en.html",
    pic: "./assets/capitaland/CLmall7.png",
  },
  {
    id: 8,
    name: "Funan Mall",
    link: "https://www.capitaland.com/sg/malls/funan/en.html",
    pic: "./assets/capitaland/CLmall8.png",
  },
  {
    id: 9,
    name: "IMM Mall",
    link: "https://www.capitaland.com/sg/malls/imm/en.html",
    pic: "./assets/capitaland/CLmall9.png",
  },
  {
    id: 10,
    name: "ION Orchard",
    link: "https://www.ionorchard.com/en/shop.html",
    pic: "./assets/capitaland/CLmall10.png",
  },
  {
    id: 11,
    name: "Jewel Changi Air",
    link: "https://www.jewelchangiairport.com/",
    pic: "./assets/capitaland/CLmall11.png",
  },
  {
    id: 12,
    name: "Junction 8",
    link: "https://www.capitaland.com/sg/malls/junction8/en.html",
    pic: "./assets/capitaland/CLmall12.png",
  },
  {
    id: 13,
    name: "Kallang Wave",
    link: "https://www.sportshub.com.sg/shop-dine/stores",
    pic: "./assets/capitaland/CLmall13.png",
  },
  {
    id: 14,
    name: "Lot One",
    link: "https://www.capitaland.com/sg/malls/lotone/en.html",
    pic: "./assets/capitaland/CLmall14.png",
  },
  {
    id: 15,
    name: "Plaza Singapura",
    link: "https://www.capitaland.com/sg/malls/plazasingapura/en.html",
    pic: "./assets/capitaland/CLmall15.png",
  },
  {
    id: 16,
    name: "Raffles City",
    link: "https://www.capitaland.com/sg/malls/rafflescity/en.html",
    pic: "./assets/capitaland/CLmall16.png",
  },
  {
    id: 17,
    name: "Senkang Grand",
    link: "https://www.sengkanggrandmall.com.sg/en.html",
    pic: "./assets/capitaland/CLmall17.png",
  },
  {
    id: 18,
    name: "SingPost Centre",
    link: "https://www.singpostcentre.com/",
    pic: "./assets/capitaland/CLmall18.svg",
  },
  {
    id: 19,
    name: "Tampines Mall",
    link: "https://www.capitaland.com/sg/malls/tampinesmall/en.html",
    pic: "./assets/capitaland/CLmall19.png",
  },
  {
    id: 20,
    name: "West Gate",
    link: "https://www.capitaland.com/sg/malls/westgate/en.html",
    pic: "./assets/capitaland/CLmall20.png",
  },
];
