// import React from 'react'

export const CentralList = [
  {
    id: 1,
    name: "100 am Mall",
    link: "https://www.100am.com.sg/",
    pic: "./assets/central/Cmall1.png",
  },
  {
    id: 2,
    name: "313 Somerset",
    link: "https://www.313somerset.com.sg/",
    pic: "./assets/central/Cmall2.svg",
  },
  {
    id: 3,
    name: "Capitol Singapore",
    link: "https://capitolsingapore.com/",
    pic: "./assets/central/Cmall3.png",
  },
  {
    id: 4,
    name: "The Cathway",
    link: "https://thecathay.com.sg/",
    pic: "./assets/central/Cmall4.webp",
  },
  {
    id: 5,
    name: "Cine Leisure",
    link: "https://cineleisure.com.sg/",
    pic: "./assets/central/Cmall5.webp",
  },
  {
    id: 6,
    name: "The CentrePoint",
    link: "https://www.thecentrepoint.com.sg/home",
    pic: "./assets/central/Cmall6.png",
  },
  {
    id: 7,
    name: "City Square Mall",
    link: "https://www.citysquaremall.com.sg/",
    pic: "./assets/central/Cmall7.png",
  },
  {
    id: 8,
    name: "City Gate",
    link: "https://www.citygate.com.sg/",
    pic: "./assets/central/Cmall8.png",
  },
  {
    id: 9,
    name: "City Link",
    link: "https://citylink.com.sg/",
    pic: "./assets/central/Cmall9.png",
  },
  {
    id: 10,
    name: "Duo Singapore",
    link: "https://duosingapore.com/",
    pic: "./assets/central/Cmall10.png",
  },
  {
    id: 11,
    name: "Far East Plaza",
    link: "https://www.fareastplaza.com.sg/",
    pic: "./assets/central/Cmall11.svg",
  },
  {
    id: 12,
    name: "Great World City",
    link: "https://shop.greatworld.com.sg/",
    pic: "./assets/central/Cmall12.png",
  },
  {
    id: 13,
    name: "GRID",
    link: "https://gridsingapore.com/",
    pic: "./assets/central/Cmall13.svg",
  },
  {
    id: 14,
    name: "Holland Village",
    link: "https://www.fareastmalls.com.sg/one-holland-village",
    pic: "./assets/central/Cmall14.svg",
  },
  {
    id: 15,
    name: "Lucky Plaza",
    link: "https://www.luckyplaza.com.sg/",
    pic: "./assets/central/Cmall15.png",
  },
  {
    id: 16,
    name: "Marina Bay Sands",
    link: "https://www.marinabaysands.com/",
    pic: "./assets/central/Cmall16.svg",
  },
  {
    id: 17,
    name: "Marina Bay Link",
    link: "https://bythebay.com.sg/",
    pic: "./assets/central/Cmall17.svg",
  },
  {
    id: 18,
    name: "Marina Square",
    link: "https://www.marinasquare.com.sg/",
    pic: "./assets/central/Cmall18.png",
  },
  {
    id: 19,
    name: "Millenia Walk",
    link: "https://www.milleniawalk.com/",
    pic: "./assets/central/Cmall19.webp",
  },
  {
    id: 20,
    name: "Mustafa",
    link: "https://www.mustafa.com.sg/",
    pic: "./assets/central/Cmall20.png",
  },
  {
    id: 21,
    name: "Takashimaya",
    link: "https://ngeeanncity.com.sg/",
    pic: "./assets/central/Cmall21.gif",
  },
  {
    id: 22,
    name: "One Holland Village",
    link: "https://www.fareastmalls.com.sg/one-holland-village",
    pic: "./assets/central/Cmall22.svg",
  },
  {
    id: 23,
    name: "Orchard Central",
    link: "https://www.fareastmalls.com.sg/orchard-central",
    pic: "./assets/central/Cmall23.png",
  },
  {
    id: 24,
    name: "Orchard Gateway",
    link: "https://orchardgateway.sg/",
    pic: "./assets/central/Cmall24.png",
  },
  {
    id: 25,
    name: "Orchard Plaza",
    link: "https://www.orchardplaza.sg/",
    pic: "./assets/central/Cmall25.png",
  },
  {
    id: 26,
    name: "Midpoint Orchard",
    link: "https://www.midpointorchard.com/",
    pic: "./assets/central/Cmall26.png",
  },
  {
    id: 27,
    name: "Palais Renaissance",
    link: "https://www.palais.sg/",
    pic: "./assets/central/Cmall27.jpg",
  },
  {
    id: 28,
    name: "Shaw Centre",
    link: "https://shawcentre.sg/",
    pic: "./assets/central/Cmall28.png",
  },
  {
    id: 29,
    name: "Sim Lim Square",
    link: "https://simlimsquare.com.sg/",
    pic: "./assets/central/Cmall29.png",
  },
  {
    id: 30,
    name: "Square 2",
    link: "https://www.fareastmalls.com.sg/square-2",
    pic: "./assets/central/Cmall30.webp",
  },
  {
    id: 31,
    name: "Sunshine Plaza",
    link: "https://www.sunshineplaza.com/",
    pic: "./assets/central/Cmall31.svg",
  },
  {
    id: 32,
    name: "Suntec City",
    link: "https://sunteccity.com.sg/",
    pic: "./assets/central/Cmall32.png",
  },
  {
    id: 33,
    name: "Tanglin Mall",
    link: "https://www.tanglinmall.com.sg/",
    pic: "./assets/central/Cmall33.png",
  },
  {
    id: 34,
    name: "Guoco Tower",
    link: "https://www.guocotower.com/",
    pic: "./assets/central/Cmall34.png",
  },
  {
    id: 35,
    name: "The Paragon",
    link: "https://paragon.com.sg/",
    pic: "./assets/central/Cmall35.png",
  },
  {
    id: 36,
    name: "Tiong Bahru Plaza",
    link: "https://www.tiongbahruplaza.com.sg/home",
    pic: "./assets/central/Cmall36.png",
  },
  {
    id: 37,
    name: "The Poiz",
    link: "https://thepoizcentre.com.sg/",
    pic: "./assets/central/Cmall37.png",
  },
  {
    id: 38,
    name: "Thomson Plaza",
    link: "https://www.thomsonplaza.com.sg/",
    pic: "./assets/central/Cmall38.png",
  },
  {
    id: 39,
    name: "United Square",
    link: "https://www.unitedsquare.com.sg/",
    pic: "./assets/central/Cmall39.png",
  },
  {
    id: 40,
    name: "Velocity",
    link: "https://www.velocitynovena.com/",
    pic: "./assets/central/Cmall40.png",
  },
  {
    id: 41,
    name: "Wisma Atria",
    link: "https://www.wismaonline.com/",
    pic: "./assets/central/Cmall41.png",
  },
  {
    id: 42,
    name: "Zhongshan Mall",
    link: "https://zhongshanmall.com.sg/",
    pic: "./assets/central/Cmall42.png",
  },
];
